# These are supported funding model platforms

github: [takielias]
patreon: takielias
open_collective: taki-elias
ko_fi: takielias
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
